# Generated by Django 4.2 on 2023-08-18 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=250)),
                ("card_id", models.CharField(blank=True, max_length=250, null=True)),
                ("card_number", models.CharField(blank=True, max_length=50, null=True)),
                ("exp_month", models.CharField(blank=True, max_length=2, null=True)),
                ("exp_year", models.CharField(blank=True, max_length=2, null=True)),
                ("cvc", models.CharField(default=123, max_length=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
