# Generated by Django 4.2 on 2023-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="balance",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
