# Generated by Django 4.2 on 2023-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_api", "0002_card_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
