# Generated by Django 4.2 on 2023-08-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_api", "0002_offlinemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receiver",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
